version = 1

test_patterns = [
  "tests/**",
  "test_*.py",
  "docs_src/**",
  "docs_*.py"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  
[[transformers]]
name = "ruff"

[[transformers]]
name = "isort"

[[transformers]]
name = "black"
